baseURL: https://manonpillot.netlify.app/
languageCode: en-us
title: Manon
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      A RESPONSIVE SITE TO PRESENT MYSELF AND MY PROJECTS.
    title: Hi, my name is Manon Pillot
  blog: {}
  contact:
    address:
      - country: Switzerland
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: mpillot.mam2023@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (+41) 0 78 732 19 19
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: London Business School
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      #- icon: fa-twitter
        #label: Twitter
        #url: https://www.twitter.com
      #- icon: fa-facebook
        #label: Facebook
        #url: https://www.facebook.com
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/manon_pillot/?hl=fr
      - icon: fa-github
        label: GitHub
        url: https://github.com/mpillot98
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/manon-pillot/
  image: ''
  name: Manon Pillot
  navigation:
    button1:
      - name: Get Started
        url: blogs
    #button2:
      #- name: Log In
        #url: '#'
    links:
      - name: Home
        url: '#'
      - name: About me
        url: blogs/about_me
      - name: Statistics project 1
        url: blogs/homework_omega
      - name: Statistics project 2
        url: blogs/homework_energy
      - name: Data science
        url: blogs/data_science
#      - name: Machine learning: Data engineering
#        url: blogs/part_1
#      - name: Machine learning: ML
#        url: blogs/part_2
#      - name: Machine learning:SVM
#        url: blogs/part_3
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: about_me.jpg
        subtitle: A short biography
        title: About me
        url: blogs/about_me
      - image: thesis.jpg
        subtitle: Esport vs. Traditionnal Sport
        title: Thesis
        url: docs/thesis.pdf
      - image: cv.jpg
        subtitle: Download my CV
        title: CV
        url: docs/CV Manon Pillot_1.pdf
#      - image: pic.jpg
#        subtitle: Why you should hire me
#        title: Cover Letter
#        url: blogs/cover_letter
      - image: omega.jpg
        subtitle: Omega analysis
        title: Statistics project 1
        url: blogs/homework_omega
      - image: energy.jpg
        subtitle: Share of renewable energy production in the world
        title: Statistics project 2
        url: blogs/homework_energy
      - image: data-science.jpg
        subtitle: BBC iPlayer streaming data
        title: Data science
        url: blogs/data_science
      - image: homicide.jpg
        subtitle: Homicide â€“ a concern across demography?
        title: Data Visualisation and Story Telling
        url: docs/Homicide_Poster.pdf
      - image: de.jpg
        subtitle: Part 1: Data engineering
        title: Machine learning
        url: blogs/data_science
#      - image: ml.jpg
#        subtitle: Part 2: ML
#        title: Machine learning
#        url: blogs/part_2
#      - image: svm.jpg
#        subtitle: Part 3: SVM
#        title: Machine learning
#        url: blogs/part_3

  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Thank you for visiting my website. Feel free to add me on social media."
    title: Contacts
    url: https://www.youtube.com/watch?v=dQw4w9WgXcQ
