baseURL: https://manonpillot.netlify.app/
languageCode: en-us
title: Manon
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      A RESPONSIVE SITE TEMPLATE DESIGNED BY HTML5 UP
      AND RELEASED UNDER THE CREATIVE COMMONS.
    title: Hi, my name is Manon Pillot
  blog: {}
  contact:
    address:
      - city: Geneva, 1206
        country: Switzerland
        street: Avenue LÃ©on Gaud
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: mpillot.mam2023@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (+41) 0 78 732 19 19
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Company Name
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - #icon: fa-twitter
        #label: Twitter
        #url: https://www.twitter.com
      - #icon: fa-facebook
        #label: Facebook
        #url: https://www.facebook.com
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/manon_pillot/?hl=fr
      - icon: fa-github
        label: GitHub
        url: https://github.com/mpillot98
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/manon-pillot/
  image: ''
  name: Manon Pillot
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum
      - name: Elements
        url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: about_me.jpg
        subtitle: A short biographie
        title: About me
        url: blogs/about_me
      - image: pic02.jpg
        subtitle: Download my CV
        title: CV
        url: blogs/cv
      - image: pic03.jpg
        subtitle: Lorem Etiam Nullam
        title: Magna
        url: blogs/magna
      - image: pic04.jpg
        subtitle: Nisl Sed Aliquam
        title: Ipsum
        url: blogs/ipsum
      - image: pic05.jpg
        subtitle: Ipsum Dolor Sit Amet
        title: Consequat
        url: blogs/ipsum
      - image: pic06.jpg
        subtitle: Feugiat Amet Tempus
        title: Etiam
        url: blogs/ipsum
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
      \r\n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \r\n    Pellentesque
      condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
      pellentesque lorem ipsum dolor. \r\n    Nullam et orci eu lorem consequat tincidunt.
      Vivamus et sagittis libero.\r\n    Mauris aliquet magna magna sed nunc rhoncus
      amet pharetra et feugiat tempus."
    title: Massa libero
    url: blogs
